### PR TITLE
feat: Fix issue #3 and issue #18

### PR DESCRIPTION
**Pull request by tobiasgg**
Implements LIC0 along with unit tests.

### CODE REVIEW

**Review by 641bill — APPROVED** [review]
LGTM, one possible improvement is to assert LENGTH1 >=0 because it is assumed in the document.

**Comment by 641bill** [comment]
Oops, Fixes #issue should be in the body of the commit or it does not close the issues I guess?

**Comment by tobiasgg** [comment]
Linked the issues now. By assert do you mean that I should throw an error if LENGTH1 < 0 or simply return False?

**Comment by 641bill** [comment]
This is what I did for LIC1,
In the LIC1 function, I put
assert RADIUS1 >= 0;
And in the LIC test, I put 
assertThrows(AssertionError.class, () -> LIC.LIC1(-1.0));
to specify it is an invalid parameter.

**Comment by tobiasgg** [comment]
Ah okay I get what you mean now when I looked at your code. I will add an issue for it and fix it.

**Pull request merged**
